### ISSUE TITLE
Design plan for Sign Language Tech

### ISSUE THREAD

**Issue by miladvafaeifard** [signlanguagetech/signlanguagetech.github.io#1]
the design should be simple and straightforward.

- [x] GitHub Action
- [x] template sample: https://vercel.com/templates/next.js/tailwind-css-starter-blog
- [ ] has dark mode
- [x] Home <- latest update
- [ ] vlogs | Glossory | Abour

**Comment by PonchoBT** [comment]
let's go to work! power!
